config/routes.rb
Sitrack::Application.routes.draw do
  resources :views do
    collection do
      get :reorder
      get :add_column
      get :remove_column
      get :search
      get :friend
      get :import
      get :borrow
      
      post :reorder
      post :add_column
      post :remove_column
      post :search
      post :friend
      post :import
      post :borrow
    end
  end

	match 'crumpd/dump' => 'crumpd#dump'
  
  match '' => 'directory#index'
  match 'modify/update' => 'modify#update'
  match 'js/options' => 'js#options', :format => 'js'

  match ':controller/service.wsdl', :action => 'wsdl'

  match 'profile/:id' => 'profile#index', :requirements => {:id => /\d+/}
                             
  match 'up_monitor' => 'application#up_monitor'
  
  match ':controller(/:action(/:id))(.:format)'
  
  resources :directory
  

end

app/views/views/_friend.html.erb
<% if @views.size > 0 %>
  <div class="segment">
    Click&nbsp;
    <%= image_tag('copy.png')%>
    &nbsp;to save the Directory Views in your list:
  </div>
  <table width="90%" id="results" cellspacing="0" class="list bordered" align="center">
    <tr>
      <td class="white sortactive" align="center" nowrap="nowrap" colspan="2">
        Directory Views
      </td>
    </tr>
    <% @views.each do |v| -%>
      <tr class="<%= cycle('odd', 'even') %>">
        <td>
          <%= v.name %><br/>
        </td>
        <td class="checkbox">
          <%=link_to image_tag('copy.png'),
            {:action => 'import', :id => v.id},
            :remote=>true, :onclick=>"$('#spinner_user_search').show();" %>
    		</td>
    	</tr>
    <% end %>
  </table>
<% else %> 
  <div class="segment">
    <br/>
  </div>
	<div class="flash_notice">No views have been created.</div>
<% end -%>

app/views/views/_list_unused.html.erb
<table width="90%" id="results" cellspacing="0" class="list unused" align="center">
  <tbody class="list">
    <tr>
      <td class="white sortactive lined-t" align="center" nowrap="nowrap" colspan="2">
        Unused Columns
      </td>
    </tr>
    <% if @unused_columns.size > 0 %>
      <% @unused_columns.each do |column| -%>
        <tr id="unused_<%=column.id%>">
          <td class="lined-l">
            <%= column.name %>
          </td>
          <td class="checkbox lined-r">
      		  <%= link_to image_tag('add.gif'), 
      				{:action => :add_column, :id => @view.id, :column_id => column.id},
      				{:remote => true, :title=>"Add Column to View"} %>
      		</td>
      	</tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="2" align="center" class="lined">
          All Columns Are Added
        </td>
    	</tr>
    <% end %>
  </tbody>
</table>

app/views/views/_list_used.html.erb
<table width="90%" id="results" cellspacing="0" class="list used" align="center" data-view-id="<%=@view.id%>">
    <tr class="not-sortable">
      <td class="white sortactive lined-t" align="center" nowrap="nowrap" colspan="2">
        Used Columns
      </td>
    </tr>
    <% if @view.sitrack_view_columns.size > 0 %>
      <% @view.sitrack_view_columns.each do |column| -%>
        <tr id="used_<%=column.id%>">
          <td class="lined-l">
            <%= column.sitrack_column.name %>
          </td>
          <td class="checkbox lined-r">
      		  <%= link_to image_tag('x.png'), 
      				{:action => :remove_column, :view_column_id => column.id},
      				{:remote => true, :title=>"Remove Column from View"} %>
      		</td>
      	</tr>
      <% end %>
    <% else %>
      <tr class="lined">
        <td colspan="2" align="center">
          No Columns Added
        </td>
    	</tr>
    <% end %>
</table>

app/views/views/_search_results.html.erb
<% if @people.size > 0 %>
  <div class="segment">
    Click&nbsp;
    <%= image_tag('forward.png')%>
    &nbsp;to see the created Directory Views of a person:
  </div>
  <table width="90%" id="results" cellspacing="0" class="list bordered" align="center">
    <tr>
      <td class="white sortactive" align="center" nowrap="nowrap" colspan="2">
        Results
      </td>
    </tr>
    <% @people.each do |p| -%>
	  	<% person = p.user.person -%>
  		<% full_name = "#{person.lastName}, #{person.firstName}" -%>
      <tr class="<%= cycle('odd', 'even') %>">
        <td>
          <%= full_name %>
          <br/>
          <span class="detail"><%= "#{p.user.username}" %></span>
        </td>
        <td class="checkbox">
          <%=link_to image_tag('forward.png'), 
            {:action => :friend, :id => p.id},
            :remote=>true, :onclick=>"$('#spinner_user_search').show();" %>
    		</td>
    	</tr>
    <% end %>
  </table>
<% else %> 
	<div class="flash_notice">There are no matches for the name you have entered.</div>
<% end -%>

app/views/views/add_column.js.erb
$("#unused_<%=@column_id%>").fadeOut();
$("#list_used").html("<%= escape_javascript(render :partial => 'list_used') %>");
initialize_sortable_manage_view_used();

app/views/views/borrow.html.erb
<div id="center">
  <div id="other_panel">
  	<div class="head">Quick Links</div>
    <div class="entry">
	    <%= link_to "Directory Views List", :action=>"index" %>
	  </div>
    <div class="entry">
	    <%= link_to "Create New View", :action=>"new" %>
	  </div>
  </div> 
  <div id="main_panel">
    <div id="holder">
	    <div class="boxheader">Find Friend's View</div>
  	  <div id="content">
  	    <div class="segment">
  	      <%= form_for(:search, :url=>{:action=>:search}, :html=>{:autocomplete=>"off", :remote=>true}) do |f| %>
            <table border="0" align="center">
      		    <tr>
      		      <td>
      			      You can search by any combination of first or last name, including partial names:
      			    </td>
                <td>
      			      <%= f.text_field :name, :value => @keyword, :onkeyup => "$('#spinner_user_search').show(); $(this).submit();" %>
      			    </td>
      			    <td width="25">
      			      <%= image_tag("spinner.gif", :id=>"spinner_user_search") %>
      			    </td>
      			  </tr>
      			</table>
      		<% end %>
      		<div id="memo_space" class="acenter">
      		</div>
  	    </div>
	    
        <div class="col1">
          <div class="boxed">
            <div class="segment" id="results">
	          
            </div>
          </div>
        </div>
        <div class="col2">
          <div class="boxed">
            <div class="segment" id="friend">
	      
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/views/edit.html.erb
<div id="center">
  <div id="other_panel">
  	<div class="head">Quick Links</div>
    <div class="entry">
	    <%= link_to "View This Directory", 
	      {:controller=>'directory', :action=>'change_view', :view_id=>@view.id} %>
	  </div>
    <div class="entry">
	    <%= link_to "Directory Views List", :action=>"index" %>
	  </div>
    <div class="entry">
	    <%= link_to "Copy Someone Else's View", :action=>"borrow" %>
	  </div>
  </div> 
  <div id="main_panel">
    <div id="holder">
	    <div class="boxheader">Edit Directory View</div>
  	  <div id="content">
  	    <% @view.errors.full_messages.each do |msg| %>
          <div class='flash_notice'><%= msg %></div>
        <% end %>
        <%= form_for(@view, :url => view_path(@view), :method => :put, :html => {:id => 'view_form'}) do |f| %>
  			  <%=render 'form', :f => f %>
  		  <% end %>
      </div>
    </div>
  </div>
</div>

app/views/views/friend.html.erb
<div id="center">
	<div class="boxheader"><%=@person.full_name%>'s views</div>
	<br>
	<div class="insidebox">
	Click on one of the views below to add it to your own tracker. Once you add it
	to your tracker any changes you make will only affect your own copy. By the same
	token, any future changes <%=@person.full_name%> makes to the view you choose 
	won't affect your copy.
	<hr/>
	<%if @views.size
		@views.each do |view|%>
			<%=link_to(view.name, :action => 'import', :id => view.id)%><br/>
	<%end
	else%>
			<strong>No views have been created.</strong>
	<%end%>
	</div>
	</div>
</div>

app/views/views/friend.js.erb
$('div#memo_space').hide();
$('div#friend').hide();
$("div#friend").html("<%= escape_javascript(render :partial=>'views/friend') %>")
$('div#friend').show('slide', {direction: 'left'});
$('#spinner_user_search').hide();

app/views/views/import.js.erb
$('div#memo_space').hide();
$("div#memo_space").html("<div class='flash_notice_ok'>Directory View named '<%= @view.name %>' is added in your list.</div>")
$('div#memo_space').fadeIn();
$('#spinner_user_search').hide();

app/views/views/index.html.erb
<div id="center">
  <div id="other_panel">
  	<div class="head">Quick Links</div>
    <div class="entry">
	    <%= link_to "Create New View", :action=>"new" %>
	  </div>
    <div class="entry">
	    <%= link_to "Copy Someone Else's View", :action=>"borrow" %>
	  </div>
  </div> 
  <div id="main_panel">
    <div id="holder">
	    <div class="boxheader">Directory Listings View</div>
  	  <div id="directory_results">
        <table cellspacing="0" border="0" width="100%" id="results">
          <% if @views.size %>
        	  <% @views.each do |view| -%>
          		<tr class="<%= cycle('odd', 'even') %>">
        				<td>
        				  <strong> 
        				    <%=view.name%>
        				  </strong>
        				</td>
    	    			<td width="170" align="center">
    	    			  <%= link_to "Edit", {:action=>'edit', :id=>view.id}, :class=>'action' %>
        				  <% href="javascript:delete_view(#{view.id},'#{escape_javascript(view.name)}')" %>
        				  <%= link_to "Remove", "#{href}", :class=>'action'%>
        				  <%= link_to "View",
        				    {:controller=>'directory', :action=>'change_view', :view_id=>view.id},
        				    :target=>'_blank', :class=>'action'%>
        				</td>
        			</tr>
        		<% end %>
        	<% else %>
        		<tr class="<%= cycle('odd', 'even') %>">
      				<td align="center">
      				  <strong> 
      				    No Created View
      				  </strong>
      				</td>
      			</tr>
      		<% end %>
      	</table>
      </div>
    </div>
  </div>
</div>

app/views/views/new.html.erb
<div id="center">
  <div id="other_panel">
  	<div class="head">Quick Links</div>
    <div class="entry">
	    <%= link_to "Directory Views List", :action=>"index" %>
	  </div>
    <div class="entry">
	    <%= link_to "Copy Someone Else's View", :action=>"borrow" %>
	  </div>
  </div> 
  <div id="main_panel">
    <div id="holder">
	    <div class="boxheader">Create New View</div>
  	  <div id="content">
  	    <% @view.errors.full_messages.each do |msg| %>
          <div class='flash_notice'><%= msg %></div>
        <% end %>
    		<br/>
        <%= form_for :view, {:action => 'new'} do |f| %>
          <center>
            <table border="0">
      		    <tr>
      		      <td>
      			      View Name:
      			    </td>
                <td>
      			      <%= f.text_field :name %>
      			    </td>
      			  </tr>
      			  <tr>
      			    <td colspan="2" align="center">
      			      <%= f.submit "Next", :class=>'button' %>
      			    </td>
      			  </tr>
      			</table>
      		</center>
      		<br/>
    		<% end %>
      </div>
    </div>
  </div>
</div>

app/views/views/remove_column.js.erb
$("#list_unused").html("<%= escape_javascript(render :partial => 'list_unused') %>");
$("#used_<%=@column_id%>").fadeOut();

app/views/views/search.js.erb
$('div#memo_space').hide();
$('#results').hide();
$("#results").html("<%= escape_javascript(render :partial => 'views/search_results') %>");
$('#results').fadeIn();
$('#spinner_user_search').hide();